-- Insert into tbl_authority
INSERT INTO tbl_authority (created_date, modified_date, title, description)
VALUES
    (NOW(), NOW(), 'HOME', 'HOME'),

    (NOW(), NOW(), 'CELL', 'Cell'),
    (NOW(), NOW(), 'CELL_RA', 'Cell (Read All)'),
    (NOW(), NOW(), 'CELL_C', 'Cell (Create)'),
    (NOW(), NOW(), 'CELL_D', 'Cell (Delete)'),
    (NOW(), NOW(), 'CELL_U', 'Cell (Update)'),

    (NOW(), NOW(), 'CELL6923', 'Cell6923'),
    (NOW(), NOW(), 'CELL6923_RA', 'Cell6923 (Read All)'),
    (NOW(), NOW(), 'CELL6923_C', 'Cell6923 (Create)'),
    (NOW(), NOW(), 'CELL6923_D', 'Cell6923 (Delete)'),
    (NOW(), NOW(), 'CELL6923_U', 'Cell6923 (Update)'),

    (NOW(), NOW(), 'COUNTY', 'County'),
    (NOW(), NOW(), 'COUNTY_RA', 'County (Read All)'),
    (NOW(), NOW(), 'COUNTY_C', 'County (Create)'),
    (NOW(), NOW(), 'COUNTY_D', 'County (Delete)'),
    (NOW(), NOW(), 'COUNTY_U', 'County (Update)'),

    (NOW(), NOW(), 'COUNTYLAB', 'CountyLab'),
    (NOW(), NOW(), 'COUNTYLAB_RA', 'CountyLab (Read All)'),
    (NOW(), NOW(), 'COUNTYLAB_C', 'CountyLab (Create)'),
    (NOW(), NOW(), 'COUNTYLAB_D', 'CountyLab (Delete)'),
    (NOW(), NOW(), 'COUNTYLAB_U', 'CountyLab (Update)'),

    (NOW(), NOW(), 'DISTRICT', 'District'),
    (NOW(), NOW(), 'DISTRICT_RA', 'District (Read All)'),
    (NOW(), NOW(), 'DISTRICT_C', 'District (Create)'),
    (NOW(), NOW(), 'DISTRICT_D', 'District (Delete)'),
    (NOW(), NOW(), 'DISTRICT_U', 'District (Update)'),

    (NOW(), NOW(), 'EXTHPV', 'ExtHpv'),
    (NOW(), NOW(), 'EXTHPV_RA', 'ExtHpv (Read All)'),
    (NOW(), NOW(), 'EXTHPV_C', 'ExtHpv (Create)'),
    (NOW(), NOW(), 'EXTHPV_D', 'ExtHpv (Delete)'),
    (NOW(), NOW(), 'EXTHPV_U', 'ExtHpv (Update)'),

    (NOW(), NOW(), 'HPV', 'Hpv'),
    (NOW(), NOW(), 'HPV_RA', 'Hpv (Read All)'),
    (NOW(), NOW(), 'HPV_C', 'Hpv (Create)'),
    (NOW(), NOW(), 'HPV_D', 'Hpv (Delete)'),
    (NOW(), NOW(), 'HPV_U', 'Hpv (Update)'),

    (NOW(), NOW(), 'INVITATIONTYPE', 'InvitationType'),
    (NOW(), NOW(), 'INVITATIONTYPE_RA', 'InvitationType (Read All)'),
    (NOW(), NOW(), 'INVITATIONTYPE_C', 'InvitationType (Create)'),
    (NOW(), NOW(), 'INVITATIONTYPE_D', 'InvitationType (Delete)'),
    (NOW(), NOW(), 'INVITATIONTYPE_U', 'InvitationType (Update)'),

    (NOW(), NOW(), 'LAB', 'Lab'),
    (NOW(), NOW(), 'LAB_RA', 'Lab (Read All)'),
    (NOW(), NOW(), 'LAB_C', 'Lab (Create)'),
    (NOW(), NOW(), 'LAB_D', 'Lab (Delete)'),
    (NOW(), NOW(), 'LAB_U', 'Lab (Update)'),

    (NOW(), NOW(), 'LABORATORY', 'Laboratory'),
    (NOW(), NOW(), 'LABORATORY_RA', 'Laboratory (Read All)'),
    (NOW(), NOW(), 'LABORATORY_C', 'Laboratory (Create)'),
    (NOW(), NOW(), 'LABORATORY_D', 'Laboratory (Delete)'),
    (NOW(), NOW(), 'LABORATORY_U', 'Laboratory (Update)'),

    (NOW(), NOW(), 'KLARTEXT', 'Klartext'),
    (NOW(), NOW(), 'KLARTEXT_RA', 'Klartext (Read All)'),
    (NOW(), NOW(), 'KLARTEXT_C', 'Klartext (Create)'),
    (NOW(), NOW(), 'KLARTEXT_D', 'Klartext (Delete)'),
    (NOW(), NOW(), 'KLARTEXT_U', 'Klartext (Update)'),

    (NOW(), NOW(), 'LOG', 'Log'),
    (NOW(), NOW(), 'LOG_RA', 'Log (Read All)'),


    (NOW(), NOW(), 'MUNICIPALITY', 'Municipality'),
    (NOW(), NOW(), 'MUNICIPALITY_RA', 'Municipality (Read All)'),
    (NOW(), NOW(), 'MUNICIPALITY_C', 'Municipality (Create)'),
    (NOW(), NOW(), 'MUNICIPALITY_D', 'Municipality (Delete)'),
    (NOW(), NOW(), 'MUNICIPALITY_U', 'Municipality (Update)'),

    (NOW(), NOW(), 'PARISH', 'Parish'),
    (NOW(), NOW(), 'PARISH_RA', 'Parish (Read All)'),
    (NOW(), NOW(), 'PARISH_C', 'Parish (Create)'),
    (NOW(), NOW(), 'PARISH_D', 'Parish (Delete)'),
    (NOW(), NOW(), 'PARISH_U', 'Parish (Update)'),

    (NOW(), NOW(), 'PERSON', 'Person'),
    (NOW(), NOW(), 'PERSON_RA', 'Person (Read All)'),
    (NOW(), NOW(), 'PERSON_C', 'Person (Create)'),
    (NOW(), NOW(), 'PERSON_U', 'Person (Update)'),
    (NOW(), NOW(), 'PERSON_D', 'Person (Delete)'),

    (NOW(), NOW(), 'PERSONSAMPLE', 'Person_Sample'),
    (NOW(), NOW(), 'PERSONSAMPLE_RA', 'Person_Sample (Read All)'),
    (NOW(), NOW(), 'PERSONSAMPLE_D', 'Person_Sample (Delete)'),

    (NOW(), NOW(), 'PERSONHPV', 'Person_Hpv'),
    (NOW(), NOW(), 'PERSONHPV_RA', 'Person_Hpv (Read All)'),
    (NOW(), NOW(), 'PERSONHPV_D', 'Person_Hpv (Delete)'),

    (NOW(), NOW(), 'PERSONEXTHPV', 'Person_ExtHpv'),
    (NOW(), NOW(), 'PERSONEXTHPV_RA', 'Person_ExtHpv (Read All)'),
    (NOW(), NOW(), 'PERSONEXTHPV_D', 'Person_ExtHpv (Delete)'),

    (NOW(), NOW(), 'PERSONCELL', 'Person_Cell'),
    (NOW(), NOW(), 'PERSONCELL_RA', 'Person_Cell (Read All)'),
    (NOW(), NOW(), 'PERSONCELL_D', 'Person_Cell (Delete)'),

    (NOW(), NOW(), 'REFERENCETYPE', 'ReferenceType'),
    (NOW(), NOW(), 'REFERENCETYPE_RA', 'ReferenceType (Read All)'),
    (NOW(), NOW(), 'REFERENCETYPE_C', 'ReferenceType (Create)'),
    (NOW(), NOW(), 'REFERENCETYPE_U', 'ReferenceType (Update)'),
    (NOW(), NOW(), 'REFERENCETYPE_D', 'ReferenceType (Delete)'),

    (NOW(), NOW(), 'SAMPLE', 'Sample'),
    (NOW(), NOW(), 'SAMPLE_RA', 'Sample (Read All)'),
    (NOW(), NOW(), 'SAMPLE_C', 'Sample (Create)'),
    (NOW(), NOW(), 'SAMPLE_U', 'Sample (Update)'),
    (NOW(), NOW(), 'SAMPLE_D', 'Sample (Delete)'),

    (NOW(), NOW(), 'SETTING', 'Setting'),
    (NOW(), NOW(), 'SETTING_U', 'Setting (Update)'),

    (NOW(), NOW(), 'SAMPLE_SHARED', 'Sample Shared'),
    (NOW(), NOW(), 'SAMPLE_UPLOAD', 'Sample Upload'),

    (NOW(), NOW(), 'UPLOAD', 'Upload'),
    (NOW(), NOW(), 'UPLOAD_C', 'Upload (Create)'),
    (NOW(), NOW(), 'UPLOAD_U', 'Upload (Update)'),
    (NOW(), NOW(), 'UPLOAD_D', 'Upload (Delete)'),

    (NOW(), NOW(), 'UPLOAD_SHARED', 'Upload Shared'),
    (NOW(), NOW(), 'UPLOAD_SHARED_C', 'Upload Shared (Create)'),
    (NOW(), NOW(), 'UPLOAD_SHARED_U', 'Upload Shared (Update)'),
    (NOW(), NOW(), 'UPLOAD_SHARED_D', 'Upload Shared (Delete)');


-- Insert into tbl_role_authority
INSERT INTO tbl_role_authority(role_id, authority_id)
VALUES
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'HOME')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LOG_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'LOG')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SETTING')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SETTING_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONSAMPLE')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONSAMPLE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONSAMPLE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONHPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONHPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONHPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONEXTHPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONEXTHPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONEXTHPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONCELL')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONCELL_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONCELL_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_UPLOAD')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_SHARED')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Super Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED_D'));

-- Insert into tbl_role_authority
INSERT INTO tbl_role_authority(role_id, authority_id)
VALUES
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'HOME')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'HPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PARISH_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'EXTHPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LABORATORY_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTY_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'COUNTYLAB_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'DISTRICT_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'INVITATIONTYPE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LAB_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LOG_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'LOG')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'CELL6923_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'MUNICIPALITY_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'KLARTEXT_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SETTING')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SETTING_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSON_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'REFERENCETYPE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONSAMPLE')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONSAMPLE_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONSAMPLE_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONHPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONHPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONHPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONEXTHPV')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONEXTHPV_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONEXTHPV_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONCELL')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONCELL_RA')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'PERSONCELL_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_D')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_UPLOAD')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'SAMPLE_SHARED')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED_C')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED_U')),
    ((SELECT id FROM tbl_role WHERE title = 'Researcher Admin'), (SELECT id FROM tbl_authority WHERE title = 'UPLOAD_SHARED_D'));
